### ISSUE TITLE
Support new MeltanoHub API with all Meltano plugin types

### ISSUE THREAD

**Issue by DouweM** [AutoIDM/tap-meltanohub#2]
https://github.com/meltano/hub#api-20-alpha

**Comment by visch** [comment]
Thank you! :D

**Comment by pnadolny13** [comment]
@visch I believe https://github.com/AutoIDM/tap-meltanohub/pull/3 closes this issue, right?

**Comment by visch** [comment]
> @visch I believe #3 closes this issue, right?

:D

You're on it! Thank you
